name: test_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  flutter_svg: ^0.19.1
  intl: ^0.16.1
  bloc: ^6.1.0
  flutter_bloc: ^6.1.1
  path_provider: ^1.6.24
  sqflite: ^1.3.2+1
  uuid: ^2.2.2
  http: ^0.12.2
  cached_network_image: ^2.4.1
  flutter_cache_manager: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  mockito: ^4.1.3
  test: ^1.15.7

flutter:
  assets:
      - assets/images/empty_tasks_bg.svg
      - assets/images/empty_tasks_second_bg.svg
      - assets/images/empty_tasks_logo.svg
      - assets/images/main_page_logo.svg

  uses-material-design: true